"""Scores added

Revision ID: 36fc588e532f
Revises: 52b1be69762e
Create Date: 2018-10-25 10:21:56.127856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fc588e532f'
down_revision = '52b1be69762e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('badge', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
