"""Third Migration

Revision ID: 38d7a361ca7b
Revises: 9f26970dfa68
Create Date: 2018-10-22 15:38:07.596051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d7a361ca7b'
down_revision = '9f26970dfa68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.String(), nullable=True))
    op.drop_column('questions', 'choice4')
    op.drop_column('questions', 'question_id')
    op.drop_column('questions', 'choice3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('choice3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('choice4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###
