"""Fifth Migration

Revision ID: 58aea1574215
Revises: d8f9cd4621b3
Create Date: 2018-10-23 12:06:11.147651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58aea1574215'
down_revision = 'd8f9cd4621b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('badge', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'badge')
    # ### end Alembic commands ###
