"""Music Migration

Revision ID: c8c9a62894cd
Revises: f4582f2d1dd1
Create Date: 2018-10-24 18:35:00.273623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c9a62894cd'
down_revision = 'f4582f2d1dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('choice1', sa.String(), nullable=True),
    sa.Column('choice2', sa.String(), nullable=True),
    sa.Column('button1', sa.String(), nullable=True),
    sa.Column('button2', sa.String(), nullable=True),
    sa.Column('div', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_question'), 'music', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_question'), table_name='music')
    op.drop_table('music')
    # ### end Alembic commands ###
