"""Marvel Migration

Revision ID: e1cdcb030d90
Revises: 58aea1574215
Create Date: 2018-10-24 14:24:34.265348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cdcb030d90'
down_revision = '58aea1574215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marvel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('choice1', sa.String(), nullable=True),
    sa.Column('choice2', sa.String(), nullable=True),
    sa.Column('button1', sa.String(), nullable=True),
    sa.Column('button2', sa.String(), nullable=True),
    sa.Column('div', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marvel_question'), 'marvel', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marvel_question'), table_name='marvel')
    op.drop_table('marvel')
    # ### end Alembic commands ###
