"""Games added

Revision ID: f4582f2d1dd1
Revises: e1cdcb030d90
Create Date: 2018-10-24 14:30:58.826458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4582f2d1dd1'
down_revision = 'e1cdcb030d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('choice1', sa.String(), nullable=True),
    sa.Column('choice2', sa.String(), nullable=True),
    sa.Column('button1', sa.String(), nullable=True),
    sa.Column('button2', sa.String(), nullable=True),
    sa.Column('div', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_question'), 'games', ['question'], unique=True)
    op.drop_index('ix_questions_question', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('choice1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('choice2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('button1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('button2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('div', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='questions_pkey')
    )
    op.create_index('ix_questions_question', 'questions', ['question'], unique=True)
    op.drop_index(op.f('ix_games_question'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
